steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/my-k8-repo/container1',
           './app1']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/my-k8-repo/container1']
  
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy pvc'
    args:
    - 'apply'
    - '-f'
    - './app1/shifa-pvc.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy Container1'
    args:
    - 'apply'
    - '-f'
    - './app1/container1-deployment.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
 

options:
  logging: CLOUD_LOGGING_ONLY


  