apiVersion: v1
kind: PersistentVolume
metadata:
  name: shifa-pv-1
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: shifa-disk
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  volumeName: shifa-pv-1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  selector:
    matchLabels:
      name: shifa-pv-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-1
  labels:
    app: container-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-1
  template:
    metadata:
      labels:
        app: container-1
    spec:
      containers:
      - name: container-2
        imagePullPolicy: Always
        image: us-central1-docker.pkg.dev/kube-429214/my-k8-repo/container1
        ports:
        - containerPort: 6000
        volumeMounts:
        - name: container1-data
          mountPath: /app/shifa_PV_dir
      volumes:
      - name: container1-data
        persistentVolumeClaim:
          claimName: pvc-1
---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: container-1
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 6000
  type: LoadBalancer
